
services:
  pgvector:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_PASSWORD: password
    networks:
      db-network:
  backend:
    image: eiparfenov/hack_minsk
    environment:
      ConnectionStrings__Postgres: 'Host=pgvector;Port=5432;Database=minsk_hack_db;Password=password;Username=postgres'
      ConnectionStrings__MlService: 'http://mlService:5000'
    ports:
      - "8080:8080"
    networks:
      db-network:
  front:
    image: midnightknight/t1_minsk_front:1.0.0
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API: "http://localhost:8080"
  mlService:
    image: adiutant/t1:v1
    networks:
      db-network:
networks:
  db-network: